version: "3"
services: 
  pizza-docker:
    build: .
    ports: 
      - "3000:3000"
    volumes: 
      - ./src:/pizza-house/src
    # environment:
    #   - CHOKIDAR_USEPOLLING=true
    env_file:
      - ./.env
